[package]
name = "shticker_book_unwritten"
version = "0.1.0"
authors = ["Dr. Jonathan Helianthicus Doe, IV <augiii@protonmail.com>"]
edition = "2018"
description = "Minimal CLI launcher for the Toontown Rewritten MMORPG"
repository = "https://github.com/JonathanHelianthicusDoe/shticker_book_unwritten"
readme = "README.md"
keywords = ["launcher", "ttr", "toontown", "rewritten", "unwritten"]
categories = ["games"]
license = "AGPL-3.0-or-later"

[dependencies]
bzip2 = "0.3.3"
clap = "2.33.0"
reqwest = "0.9.20"
rpassword = "4.0.1"
serde = { version = "1.0.99", features = ["derive"] }
serde_json = "1.0.40"
sha-1 = "0.8.1"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = "fat"
debug-assertions = false
codegen-units = 1
panic = "abort"
incremental = false
overflow-checks = false
